title:   Ipek Basman
logo: "/WhatsApp_Image_2024-06-06_at_5.12.04_PM-removebg-preview.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  I'm a data analyst  with a knack for turning complex data into actionable insights.Leveraging my expertise to bridge the business-data gap. My expertise lies in data analysis using SQL, Python, and Power BI, allowing me to automate dashboards, streamline workflows, and empower stakeholders with clear and concise communication. I excel at uncovering behavioral patterns, pinpointing business challenges, and crafting data-driven solutions that drive value for both internal teams and external customers.
  <br> 
  <br> 
  <a href="https://www.linkedin.com/in/ipek-ba%C5%9Fman/">View My LinkedIn Profile</a>
  <br>
  <br> 
  <a href="https://ipekbasman.notion.site/Ipek-Basman-s-Portfolio-8e31eddec07f4d7990dbb1da23f255f8?pvs=4">View My Notion Portfolios</a>
theme: jekyll-theme-minimal   
  
 
